### ISSUE TITLE
memtype_cache.c:83 ERROR failed to insert region : Element already exists

### ISSUE THREAD

**Issue by paklui** [ROCmSoftwarePlatform/ucx#1]
### Describe the bug
memtype_cache.c shows error for failed to insert region. The error may be related to rocm_ipc cache but it does not appear to interfere with the run or performance.

```
[1576598290.974585] [ixt-hq-50:11208:0]  memtype_cache.c:83   UCX  ERROR failed to insert region 0x564d28b40a50 [0x7f6634000000..0x7f66349ea010]: Element already exists
```

### Steps to Reproduce
- Command line
```
(myenv) hoomd@ixt-hq-50:~/hoomd-benchmarks$
mpirun -np 2 /home/hoomd/miniconda3/envs/myenv/bin/python3 project.py run lj_liquid-benchmark-gpu_np1
```
- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)

```
(myenv) hoomd@ixt-hq-50:~/hoomd-benchmarks$ ucx_info -v
# UCT version=1.7.0 revision 18b0018
# configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/usr
```

- **Any UCX environment variables used**

[log.hoomd-blue-2np-ixt-hq-50-191214_185517.txt](https://github.com/ROCmSoftwarePlatform/ucx/files/3974919/log.hoomd-blue-2np-ixt-hq-50-191214_185517.txt)

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`
```
(myenv) hoomd@ixt-hq-50:~/hoomd-benchmarks$ cat /etc/issue
Ubuntu 18.04.3 LTS \n \l

(myenv) hoomd@ixt-hq-50:~/hoomd-benchmarks$ uname -a
Linux ixt-hq-50 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- For RDMA/IB/RoCE related issues:
    - Driver version:
        - `rpm -q rdma-core` or `rpm -q libibverbs`
        - or: MLNX_OFED version `ofed_info -s`
   - HW information from `ibstat` or `ibv_devinfo -vv` command
- For GPU related issues:
  - GPU type
  - Cuda: 
      - Drivers version
      - Check if peer-direct is loaded: `lsmod|grep nv_peer_mem` and/or gdrcopy: `lsmod|grep gdrdrv`

```
(myenv) hoomd@ixt-hq-50:~/hoomd-benchmarks$ apt show rocm-libs -a
Package: rocm-libs
Version: 2.10.14
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices Inc.
Installed-Size: 13.3 kB
Depends: rocfft, rocrand, rocblas, hipblas, rocsparse, hipsparse, rocalution, rocprim, rocthrust, hipcub
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: 798 B
APT-Manual-Installed: yes
APT-Sources: http://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
Description: Radeon Open Compute (ROCm) Runtime software stack
```

### Additional information (depending on the issue)
- OpenMPI version
```
(myenv) hoomd@ixt-hq-50:~/hoomd-benchmarks$ mpirun --version
mpirun (Open MPI) 4.0.2rc3
```
- Output of `ucx_info -d` to show transports and devices recognized by UCX
- Configure result - config.log
- Log file - configure UCX with "--enable-logging" - and run with "UCX_LOG_LEVEL=data"

**Comment by souravzzz** [comment]
Possible fix in https://github.com/openucx/ucx/pull/4466

**Comment by dmitrygx** [comment]
@paklui could you try openucx#4466, pls?

**Comment by paklui** [comment]
The fix appears to be working, I don't see that error anymore. Thank you @dmitrygx @souravzzz for the suggestion.

**Comment by dmitrygx** [comment]
> The fix appears to be working, I don't see that error anymore. Thank you @dmitrygx @souravzzz for the suggestion.

@paklui thank you for testing the PR.
the PR will be merged to the UCX master in a couple of days.
